# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
print(np.__version__)

2.3.1


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
z=np.zeros(10) 
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [9]:
print(z.itemsize)

8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
z=np.zeros(10)
z[4]=1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
flipped_x=np.flip(x)
print(flipped_x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
matrix_a=np.arange(0,9).reshape(3,3)
print(matrix_a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [24]:
arr=np.array([1,2,0,0,4,0])
arr=np.nonzero(arr)[0]
print(arr)

[0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [6]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [8]:
matrix_3=np.random.rand(3,3,3)
print(matrix_3)

[[[0.43435274 0.53238109 0.66457568]
  [0.76983113 0.35553705 0.20950918]
  [0.49196771 0.99923216 0.9926786 ]]

 [[0.13205455 0.56212119 0.07725512]
  [0.9384941  0.81028985 0.52160127]
  [0.59824516 0.67801372 0.0152967 ]]

 [[0.65111153 0.60161659 0.92660568]
  [0.7270223  0.91151203 0.95509577]
  [0.68764067 0.99111805 0.45409011]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [12]:
matrix_10=np.random.rand(10,10)
print(np.min(matrix_10))
print(np.max(matrix_10))

0.02972124119093067
0.9940181415483806


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
y=np.random.rand(30)
print(np.mean(y))

0.537085078257171


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
z=np.ones((4,4))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
arr = np.ones((3, 3))
bordered = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(bordered)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
print("0 * np.nan:", 0 * np.nan)                        # nan
print("np.nan == np.nan:", np.nan == np.nan)            # False
print("np.inf > np.nan:", np.inf > np.nan)              # False
print("np.nan - np.nan:", np.nan - np.nan)              # nan
print("np.nan in set([np.nan]):", np.nan in set([np.nan]))  # True!
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)    

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [30]:
five=np.zeros((5,5))
np.fill_diagonal(five[1:], [1, 2, 3, 4])
print(five)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [39]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [40]:
print(np.unravel_index(100, (6, 7, 8)))

(np.int64(1), np.int64(5), np.int64(4))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [5]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 0.79684388  0.59587027  1.20586105 -0.87988516  1.5873952 ]
 [-0.6522117   0.77666066 -1.41182699  0.73401637  0.53463298]
 [-1.23271979  0.54578093 -0.91957894  0.84966242  1.22847383]
 [-1.04823637  1.01155711 -0.93279331 -1.60949114  1.20030678]
 [-1.44448886 -0.7461224  -0.04843959  0.57833164 -0.71959887]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [8]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [9]:
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [10]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [11]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [4]:
Z = np.array([1, 2, 3])

print(Z**Z)           # [ 1  4 27]
print(2 << Z >> 2)    # [0 0 0]
print(Z < -Z)         # [False False False]
print(1j * Z)         # [0.+1.j 0.+2.j 0.+3.j]
print(Z / 1 / 1)      # [1. 2. 3.]


[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [7]:
import warnings
warnings.filterwarnings('ignore')

print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [16]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[  3.   5.  -6. -10.   2.   2.  -6.   5.   8.  -6.]


#### 30. How to find common values between two arrays? (★☆☆)

In [17]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 5 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [3]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z - v)).argmin()
print(Z[index])

59


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [9]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(), dtype=int, count=-1)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.10983279 0.12188144 0.4449678  0.50593491 0.60047886 0.67940939
 0.69675539 0.71105239 0.77551316 0.77562817]


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.54857201 0.         0.39551265 0.79973282 0.05798344 0.14092975
 0.38586413 0.61985467 0.48030379 0.19717805]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [10]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [11]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.round(C, 3))

[[-2.    -0.667 -0.4   -0.286 -0.222 -0.182 -0.154 -0.133]
 [ 2.    -2.    -0.667 -0.4   -0.286 -0.222 -0.182 -0.154]
 [ 0.667  2.    -2.    -0.667 -0.4   -0.286 -0.222 -0.182]
 [ 0.4    0.667  2.    -2.    -0.667 -0.4   -0.286 -0.222]
 [ 0.286  0.4    0.667  2.    -2.    -0.667 -0.4   -0.286]
 [ 0.222  0.286  0.4    0.667  2.    -2.    -0.667 -0.4  ]
 [ 0.182  0.222  0.286  0.4    0.667  2.    -2.    -0.667]
 [ 0.154  0.182  0.222  0.286  0.4    0.667  2.    -2.   ]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [12]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [13]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [14]:
np.set_printoptions(suppress=True)
Z = np.random.random((2,2)) * 1e4
print(Z)

[[5322.94080846  219.88388056]
 [3233.83063523  496.02201315]]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [15]:
Z = np.arange(25).reshape(5,5)
Z[[0,1]] = Z[[1,0]]
print(Z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [16]:
Z = np.arange(25).reshape(5,5)
Z[:, [0,1]] = Z[:, [1,0]]
print(Z)

[[ 1  0  2  3  4]
 [ 6  5  7  8  9]
 [11 10 12 13 14]
 [16 15 17 18 19]
 [21 20 22 23 24]]


#### 43. Make an array immutable (read-only) (★★☆)

In [17]:
Z = np.random.random((3,4,5))
Z = Z.swapaxes(1,2)
print(Z.shape)

(3, 5, 4)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [18]:
Z = np.linspace(0, 1, 100)
print(Z)

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [19]:
Z = np.arange(42).reshape(6,7)
print(Z)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [20]:
Z = np.arange(42).reshape(6,7)
print(Z)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [21]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.round(C, 3))

[[-2.    -0.667 -0.4   -0.286 -0.222 -0.182 -0.154 -0.133]
 [ 2.    -2.    -0.667 -0.4   -0.286 -0.222 -0.182 -0.154]
 [ 0.667  2.    -2.    -0.667 -0.4   -0.286 -0.222 -0.182]
 [ 0.4    0.667  2.    -2.    -0.667 -0.4   -0.286 -0.222]
 [ 0.286  0.4    0.667  2.    -2.    -0.667 -0.4   -0.286]
 [ 0.222  0.286  0.4    0.667  2.    -2.    -0.667 -0.4  ]
 [ 0.182  0.222  0.286  0.4    0.667  2.    -2.    -0.667]
 [ 0.154  0.182  0.222  0.286  0.4    0.667  2.    -2.   ]]


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [22]:
for dtype in [np.int8, np.int32, np.int64]:
    print(dtype, ":", np.iinfo(dtype).min, np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(dtype, ":", np.finfo(dtype).min, np.finfo(dtype).max)

<class 'numpy.int8'> : -128 127
<class 'numpy.int32'> : -2147483648 2147483647
<class 'numpy.int64'> : -9223372036854775808 9223372036854775807
<class 'numpy.float32'> : -3.4028235e+38 3.4028235e+38
<class 'numpy.float64'> : -1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [23]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [24]:
Z = np.arange(100)
v = 56.7
index = (np.abs(Z - v)).argmin()
print(Z[index])

57


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [25]:
Z = np.zeros(10, dtype=[('position', [('x', float), ('y', float)]),
                        ('color',    [('r', float), ('g', float), ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [26]:
Z = np.random.rand(100, 2)
X, Y = np.atleast_2d(Z[:, 0], Z[:, 1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.274545   0.58650424 0.64041449 0.55035119 0.29458746
  0.71786006 0.52032261 0.43042922 0.55037054 0.31534634 0.75430391
  0.5115597  0.19823703 0.69487176 0.38036162 0.56265435 0.31343082
  0.53370232 0.57605312 0.13981795 0.3282413  0.68483731 0.12371044
  0.21492746 0.57997533 0.17299494 0.44282448 0.0475938  0.71604005
  0.31316143 0.34712199 0.33512439 0.53757288 0.81438481 0.25847368
  0.5685815  0.37053984 0.45439186 0.51746156 0.73320995 0.34364912
  0.17895914 0.58261199 0.16365407 0.31726227 0.18142852 0.47600655
  0.188392   0.24486295 0.1476036  0.67313683 0.23326286 0.43431887
  0.29546033 0.25905889 0.48769733 0.11701438 0.42722759 0.02481715
  0.13956533 0.18326912 0.28279648 0.55028691 0.29133005 0.4097174
  0.71831059 0.28179862 0.69891304 0.70655003 0.60242684 0.70173413
  0.63086208 0.54367841 0.54957076 0.79748632 0.76114697 0.05691651
  0.1508259  0.53928373 0.65731597 0.47360883 0.33136052 0.48310086
  0.59860469 0.58628983 0.48592411 0.39164098 0.4

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [27]:
Z = (np.random.rand(10) * 100).astype(np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[10 98 98 76 39 81 93 10 75 27]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [29]:
from io import StringIO

s = StringIO("1, 2, 3, 4, 5\n6, , , 7, 8\n , , 9,10,11")
Z = np.genfromtxt(s, delimiter=",")
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [30]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [31]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [32]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X**2 + Y**2)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D - mu)**2 / (2.0 * sigma**2) ))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [33]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.19648331  0.53396177  0.27990996 -0.145637    0.39661839 -0.40668759
  -0.16310077 -0.14420766 -0.27038664 -0.27695375]
 [ 0.16672194 -0.35386007  0.24216436  0.3550017  -0.42720173  0.42864867
   0.17687209 -0.45869957  0.14848017 -0.27812756]
 [-0.27915305 -0.14219665  0.1543859  -0.4288204  -0.15143406  0.1369107
  -0.19001943  0.30155155  0.51493894  0.0838365 ]
 [ 0.29324298 -0.12883431  0.10376037 -0.12766844 -0.33051497  0.07709553
   0.12207436  0.01857562 -0.359908    0.33217688]
 [ 0.2534616   0.27973531  0.01369881 -0.46554825  0.08900006 -0.2361507
   0.10244341  0.31559108  0.05123313 -0.40346444]]


#### 59. How to sort an array by the nth column? (★★☆)

In [34]:
Z = np.random.randint(0, 10, (5, 5))
print("Before:\n", Z)
Z = Z[Z[:, 1].argsort()]
print("After:\n", Z)

Before:
 [[8 5 1 0 5]
 [3 0 6 8 9]
 [5 0 8 8 2]
 [9 6 5 5 8]
 [7 9 2 3 0]]
After:
 [[3 0 6 8 9]
 [5 0 8 8 2]
 [8 5 1 0 5]
 [9 6 5 5 8]
 [7 9 2 3 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [35]:
Z = np.random.randint(0, 2, (10, 10))
print((~Z.any(axis=0)).any()) 

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [36]:
Z = np.random.uniform(0, 1, 10)
val = 0.5
print(Z[np.abs(Z - val).argmin()])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [38]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [37]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "my_array")
print(Z.name)

my_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [2]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
np.add.at(Z, I, 1)
print(Z)

[1. 4. 4. 3. 3. 3. 3. 3. 2. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [3]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [4]:
w, h = 16, 16
I = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)
F = I.reshape(-1, 3)
n_colors = len(np.unique(F, axis=0))
print(n_colors)

256


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [5]:
w, h = 16, 16
I = np.random.randint(0, 256, (w, h, 3), dtype=np.uint8)
F = I.reshape(-1, 3)
n_colors = len(np.unique(F, axis=0))
print(n_colors)

256


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [6]:
D = np.random.rand(100)
S = np.random.randint(0, 10, 100)
mean = np.bincount(S, weights=D) / np.bincount(S)
print(mean)

[0.40134695 0.49339412 0.61253258 0.47253585 0.66971471 0.30362089
 0.44206079 0.48648087 0.40848073 0.46751468]


#### 69. How to get the diagonal of a dot product? (★★★)

In [7]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
diag = np.sum(A * B.T, axis=1)
print(diag)

[0.56156787 1.02035344 0.54635325]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [8]:
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*nz, dtype=int)
Z0[::nz+1] = Z
print(Z0)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [9]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [10]:
A = np.arange(25).reshape(5, 5)
A[[0, 1]] = A[[1, 0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [11]:
triangles = np.random.randint(0, 100, (10, 3))
edges = np.sort(np.concatenate([triangles[:, [0, 1]],
                                triangles[:, [1, 2]],
                                triangles[:, [2, 0]]]), axis=1)
edges = np.unique(edges, axis=0)
print(edges)

[[ 9 16]
 [ 9 92]
 [13 18]
 [13 39]
 [16 92]
 [18 39]
 [23 89]
 [23 98]
 [26 26]
 [26 70]
 [32 60]
 [32 86]
 [33 70]
 [33 94]
 [34 69]
 [34 96]
 [41 58]
 [41 93]
 [43 84]
 [43 97]
 [58 93]
 [60 86]
 [69 96]
 [70 94]
 [73 81]
 [73 95]
 [81 95]
 [84 97]
 [89 98]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [12]:
C = np.bincount([1, 1, 2, 3, 3, 3])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 3 3]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [13]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [14]:
Z = np.arange(10)
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [15]:
Z = np.array([True, False, True])
Z = ~Z
print(Z)

F = np.array([1, -2, 3])
F *= -1
print(F)

[False  True False]
[-1  2 -3]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [16]:
def distance_point_to_line(P0, P1, p):
    T = P1 - P0
    L = np.sum((T)**2, axis=1)
    u = np.sum((p - P0) * T, axis=1) / L
    d = np.linalg.norm(P0 + u[:, None] * T - p, axis=1)
    return d

P0 = np.random.rand(10, 2)
P1 = np.random.rand(10, 2)
p = np.random.rand(2)
print(distance_point_to_line(P0, P1, p))

[0.94153597 0.53173045 0.59575731 0.26105794 0.01658633 0.54761783
 0.67241306 0.15396415 0.18895721 0.67799903]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [17]:
P0 = np.random.rand(5, 2)
P1 = np.random.rand(5, 2)
P = np.random.rand(10, 2)

dists = np.empty((len(P0), len(P)))
for i in range(len(P0)):
    T = P1[i] - P0[i]
    L = np.sum(T**2)
    u = np.dot(P - P0[i], T) / L
    proj = P0[i] + u[:, None] * T
    dists[i] = np.linalg.norm(P - proj, axis=1)

print(dists)

[[0.3060195  0.18637991 0.34761692 0.03614964 0.00622925 0.20693168
  0.26814596 0.44605297 0.00725536 0.01002418]
 [0.02681416 0.60476626 0.27594598 0.02386152 0.55113895 0.75243521
  0.74256947 0.03156635 0.09335563 0.33520668]
 [0.3913974  0.0384787  0.22888502 0.16617957 0.07552866 0.32042448
  0.04308236 0.49931057 0.10446928 0.00189056]
 [0.32720934 0.02055813 0.77702405 0.56841017 0.2057393  0.27586979
  0.20796802 0.1859704  0.5614118  0.38373545]
 [0.5979029  0.01973954 0.16612751 0.48402289 0.01948242 0.2101755
  0.07843713 0.63833161 0.41256466 0.20233047]]


#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [18]:
def extract_subarray(Z, center, shape, fill=0):
    output = np.full(shape, fill)
    Z = np.pad(Z, [(s//2, s//2) for s in shape], constant_values=fill)
    c = [c + s//2 for c, s in zip(center, shape)]
    slices = tuple(slice(c[i] - shape[i]//2, c[i] + shape[i]//2 + 1) for i in range(len(shape)))
    return Z[slices]

Z = np.random.randint(0, 10, (5, 5))
print(Z)
print(extract_subarray(Z, (2, 2), (3, 3)))

[[6 3 3 7 8]
 [3 7 8 0 0]
 [5 1 6 9 4]
 [8 6 7 7 8]
 [9 8 1 3 6]]
[[7 8 0]
 [1 6 9]
 [6 7 7]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [19]:
Z = np.arange(1, 15)
R = np.lib.stride_tricks.sliding_window_view(Z, 4)
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [20]:
Z = np.random.rand(10, 10)
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [21]:
Z = np.random.randint(0, 10, 50)
most_freq = np.bincount(Z).argmax()
print(most_freq)

9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [22]:
Z = np.random.randint(0, 10, 50)
most_freq = np.bincount(Z).argmax()
print(most_freq)

3


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [23]:
Z = np.random.rand(10, 10)
block3x3 = np.lib.stride_tricks.sliding_window_view(Z, (3, 3))
print(block3x3.shape)

(8, 8, 3, 3)


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [24]:
p, n = 5, 3
M = np.random.rand(p, n, n)
V = np.random.rand(p, n, 1)
S = np.einsum('ijk,ikl->jl', M, V)
print(S)

[[2.48802341]
 [3.25350156]
 [2.71265001]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [25]:
Z = np.random.rand(16, 16)
block_sum = Z.reshape(4, 4, 4, 4).sum(axis=(2, 3))
print(block_sum)

[[6.88243215 8.58469014 9.65156745 8.70925156]
 [7.52716293 5.66711153 8.68678622 6.80882665]
 [6.40726201 8.0410058  8.7971409  7.29811774]
 [6.47519344 7.97211714 8.33449271 7.82917726]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [26]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2] +               Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N == 3) & (Z[1:-1,1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (10, 10))
iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 1 0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [0 1 0 1 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [27]:
Z = np.random.rand(100)
n = 5
print(Z[np.argpartition(-Z, n)[:n]])

[0.98506118 0.98248701 0.98096448 0.94953273 0.93892378]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [28]:
def cartesian_product(*arrays):
    return np.array(np.meshgrid(*arrays)).T.reshape(-1, len(arrays))

print(cartesian_product([1, 2], [3, 4], [5, 6]))

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


#### 91. How to create a record array from a regular array? (★★★)

In [29]:
Z = np.array([[1, 2.0], [3, 4.0]], dtype='f8,f8')
print(Z)

[[(1., 1.) (2., 2.)]
 [(3., 3.) (4., 4.)]]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [30]:
Z = np.arange(10)
print(Z ** 3)
print(np.power(Z, 3))
print(np.multiply(Z, Z*Z))

[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]
[  0   1   8  27  64 125 216 343 512 729]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [31]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))

mask = np.array([np.all(np.isin(b, row)) for row in A for b in B]).reshape(len(A), len(B))
rows = A[np.any(mask, axis=1)]
print(rows)

[[4 0 1]
 [1 4 0]
 [1 4 0]
 [2 1 4]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [32]:
Z = np.random.randint(0, 5, (10, 3))
print(Z[~(Z[:, 0] == Z[:, 1]) | ~(Z[:, 1] == Z[:, 2])])

[[2 3 3]
 [4 1 3]
 [4 2 0]
 [2 0 2]
 [0 3 3]
 [1 4 1]
 [3 4 1]
 [2 3 0]
 [0 4 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [33]:
Z = np.arange(10)
print(((Z[:, None] & (1 << np.arange(8))) > 0).astype(int))

[[0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 1 0 0 0 0 0]
 [1 1 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 1 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [38]:
Z = np.random.randint(0, 2, (10, 3))
print(np.unique(Z, axis=0))

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [37]:
A = np.array([1, 2])
B = np.array([3, 4])

print(np.einsum('i,i->', A, B))    # Inner product
print(np.einsum('i,j->ij', A, B))  # Outer product
print(np.einsum('i->', A))         # Sum
print(np.einsum('i,i->i', A, B))   

11
[[3 4]
 [6 8]]
3
[3 8]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [36]:
X = np.cumsum(np.random.rand(10))
Y = np.cumsum(np.random.rand(10))
dist = np.sqrt(np.diff(X)**2 + np.diff(Y)**2)
dist = np.insert(np.cumsum(dist), 0, 0)
alpha = np.linspace(0, dist[-1], 100)
X_out = np.interp(alpha, dist, X)
Y_out = np.interp(alpha, dist, Y)
print(X_out, Y_out)

[0.56859942 0.6221602  0.67572098 0.72928175 0.78284253 0.83640331
 0.88996409 0.94352487 0.99708565 1.05064643 1.10420721 1.15776799
 1.21132877 1.26488955 1.31845033 1.37201111 1.42557189 1.48001852
 1.53739405 1.59476958 1.65214511 1.70952064 1.76689617 1.8242717
 1.88164723 1.93902276 1.99639829 2.05377382 2.11114934 2.16852487
 2.2259004  2.28327593 2.34065146 2.39145211 2.44167134 2.48058561
 2.49866437 2.51674314 2.5348219  2.55290067 2.57097943 2.59890174
 2.6485499  2.69819806 2.74784622 2.79749438 2.84714255 2.89679071
 2.94643887 2.99608703 3.04573519 3.09538335 3.14503151 3.19467968
 3.24432784 3.293976   3.34362416 3.39327232 3.44292048 3.49540587
 3.54798643 3.600567   3.65314756 3.70572812 3.75830868 3.81088924
 3.86346981 3.91605037 3.96863093 4.02121149 4.06595092 4.10939974
 4.15284857 4.19629739 4.23974622 4.28319504 4.32664387 4.37009269
 4.41354151 4.45699034 4.50043916 4.54388799 4.55502947 4.56249639
 4.5699633  4.57743022 4.58489713 4.60524131 4.62577625 4.64631

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [40]:
n = 10
X = np.random.randint(0, 5, (100, 5))
print(X[X.sum(axis=1) == n])

[[1 1 2 2 4]
 [2 3 3 1 1]
 [4 3 2 0 1]
 [4 1 3 1 1]
 [1 1 4 1 3]
 [4 3 2 1 0]
 [2 2 1 2 3]
 [1 4 3 1 1]
 [3 3 0 0 4]
 [0 3 4 0 3]
 [1 0 4 3 2]
 [4 4 0 2 0]
 [1 1 2 4 2]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [34]:
X = np.random.rand(100)
N = 1000
means = [np.mean(np.random.choice(X, size=X.size, replace=True)) for _ in range(N)]
conf_int = np.percentile(means, [2.5, 97.5])
print(conf_int)

[0.48085842 0.58841378]
